# Generated by Django 5.1.3 on 2025-01-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_scorer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scorer',
        ),
    ]
