# Generated by Django 5.1.3 on 2024-11-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
    ]
