# Generated by Django 5.1.3 on 2024-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_goals_conceded_team_goals_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
