# Generated by Django 5.1.3 on 2024-11-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_league_name'),
        ('users', '0003_remove_user_age_user_team_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leagues_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_leagues', to='leagues.league'),
        ),
    ]
