# Generated by Django 5.1.3 on 2024-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_created_by'),
        ('users', '0004_user_leagues_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='players', to='teams.team'),
        ),
    ]
