# Generated by Django 5.1.3 on 2025-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
